# Generated by Django 4.2 on 2023-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='family',
            field=models.CharField(choices=[('GBX', 'Genbox'), ('MT4', 'Metatrader4'), ('MT5', 'Metatrader5'), ('STM', 'Statement'), ('UP', 'Uploaded From File')], default='GBX', max_length=12),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='initial_balance',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=6),
        ),
    ]
