# Generated by Django 4.2 on 2023-04-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='timeframe',
            field=models.CharField(choices=[('M1', 'One Minute'), ('M5', 'Five Minutes'), ('M15', 'Fifteen Minutes'), ('M30', 'Thirteen Minutes'), ('H1', 'One Hour'), ('H4', 'Four Hours'), ('D1', 'Daily'), ('W', ' Weekly'), ('M', 'Monthly')], default='H4', max_length=3),
        ),
    ]
