# Generated by Django 4.2 on 2023-04-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancho', '0002_alter_backtest_family_alter_backtest_initial_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='es',
            new_name='ep',
        ),
        migrations.AlterField(
            model_name='backtest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
